name: Markyun
description: "Front-End Engineer"
meta_description: "前端开发工程师"

aboutPage: true
paginate: 30
markdown: redcarpet
highlighter: pygments
# pygments: true
baseurl: /
domain_name: 'http://markyun.github.io'
# google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'markyungithub'

# Details for the RSS feed generator
url:            'http://markyun.github.io'
author:         'markyun'
authorTwitter:  'markyun'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post

live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: live2d-widget-model-hijiki
  display:
    position: right
    width: 150
    height: 300
  mobile:
    show: true